# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edc0856119ae3a66ebab7a879d01c87ed1df78eb9f33cb7cd4a25b955916f240f2ec9aaea1ea958d06d03000f813d5d2c02b8c51a69a2e738a96e28087370d98

test:
  secret_key_base: 7e03db9939ae7f5b95b657875ea025a6ee45c2b901f9d6e33efbd74fffabdee319262b6951b38e4c7682b9de5610f3665066ad6cc5e225c5cb007e6bff1ce418

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
